module.exports = {
  apps: [
    {
      name: 'teamclaw-server',
      script: './server/src/index.ts',
      interpreter: 'tsx',
      cwd: './',
      watch: ['./server/src'],
      ignore_watch: ['node_modules', '.next', 'dist'],
      env: {
        NODE_ENV: 'production',
        PORT: 9700,
        HOST: 'localhost',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 9700,
        HOST: '0.0.0.0',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      kill_timeout: 5000,
      listen_timeout: 3000,
    },
    {
      name: 'teamclaw-dashboard',
      script: 'npx',
      args: 'next start -p 3000',
      cwd: './',
      watch: ['./app', './components', './lib'],
      ignore_watch: ['node_modules', '.next'],
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
